export const ROUTE_PATH = {
  HOME: '/',
  DROPS: '/art-on-bitcoin',
  CREATE_PROJECT: '/create',
  BENEFIT: '/create',
  GENERATIVE: '/generative',
  GENERATIVE_EDIT: '/generative/edit',
  PROFILE: '/profile',
  EDIT_PROFILE: `/profile/edit`,
  SANDBOX: '/sandbox',
  DISPLAY: '/grail',
  ORDER_NOW: '/order-now',
  LEADERBOARDS: '/leaderboards',
  DAO: '/dao',
  INCENTIVIZED_TESTNET: '/incentivized-testnet',
  TRADE: '/marketplace',
  LIVE: '/live',
  REFERRAL: '/referral',
  NOT_FOUND: '/404',
  INSCRIBE: '/inscribe',
  CREATE_BTC_PROJECT: '/create',
  GLTF_PREVIEW: '/gltf-preview',
  OBJECT_PREVIEW: '/object-preview',
  SATOSHIS_FREE_MINT: '/satoshis/free',
  SATOSHIS_PAGE: '/satoshis',
  WALLET: '/wallet',
  ARTISTS: '/artists',
  SEARCH: '/search',
  FREE_INSCRIPTION: '/free',
  AUTHENTIC: '/authentic',
  AIRDROP: '/airdrop',
  MINT_STATUS: '/mint-status',
};

export const STANDALONE_PAGES = [
  ROUTE_PATH.GLTF_PREVIEW,
  ROUTE_PATH.OBJECT_PREVIEW,
];
