export const BTC_PROJECT = {
  LAUNCH_NEW_PROJECT: 'BTC_PROJECT-LAUNCH_NEW_PROJECT',
  MINT_NFT: 'BTC_PROJECT-MINT_NFT',
  REPORT_PROJECT: 'BTC_PROJECT-REPORT_PROJECT',
  SHARE_REFERRAL_LINK: 'BTC_PROJECT-SHARE_REFERRAL_LINK',
  WITHDRAW: 'BTC_PROJECT-WITHDRAW',
  REFERRED_USER: 'BTC_PROJECT-REFERRED_USER',
};
