export const BTC_PROJECT = {
  LAUNCH_NEW_PROJECT: 'BTC_PROJECT-LAUNCH_NEW_PROJECT',
  MINT_NFT: 'BTC_PROJECT-MINT_NFT',
  REPORT_PROJECT: 'BTC_PROJECT-REPORT_PROJECT',
  CLICK_PROJECT: 'BTC_PROJECT-CLICK_PROJECT',
};
